# Use this file when compiling on WINDOWS, set the airsdk variable bellow to your airsdk path
# and then specify this file when you run meson:
#
# meson setup build --native-file airsdk.windows.ini
#

[constants]
airsdk = ''

[binaries]
mxmlc = airsdk / 'bin\mxmlc.bat'
compc = airsdk / 'bin\compc.bat'