# Use this file when compiling on MAC or LINUX, set the airsdk variable bellow to your airsdk path
# and then specify this file when you run meson:
#
# meson setup build --native-file airsdk.ini
#

[constants]
airsdk = ''

[binaries]
mxmlc = airsdk / 'bin/mxmlc'
compc = airsdk / 'bin/compc'