tanks_sources = files(
    'alternativa/tanks/game/camera/AxisIndicator.as',
    'alternativa/tanks/game/camera/CameraControllerBase.as',
    'alternativa/tanks/game/camera/FollowCameraController.as',
    'alternativa/tanks/game/camera/FreeCameraController.as',
    'alternativa/tanks/game/camera/OrbitCameraController.as',

    'alternativa/tanks/game/effects/AnimatedPlaneEffect.as',
    'alternativa/tanks/game/effects/AnimatedSpriteEffect.as',
    'alternativa/tanks/game/effects/Blinker.as',
    'alternativa/tanks/game/effects/ColorTransformEntry.as',
    'alternativa/tanks/game/effects/debug/FloatingTextEffect.as',
    'alternativa/tanks/game/effects/Fire.as',
    'alternativa/tanks/game/effects/IAreaOfEffectSFX.as',
    'alternativa/tanks/game/effects/MovingAnimatedSprite.as',
    'alternativa/tanks/game/effects/Plane.as',
    'alternativa/tanks/game/effects/SimpleWeaponShotSFXComponent.as',
    
    'alternativa/tanks/game/entities/EmptyState.as',
    'alternativa/tanks/game/entities/EventStates.as',
    'alternativa/tanks/game/entities/IComponentState.as',
    'alternativa/tanks/game/entities/map/A3DMapBuilder.as',
    'alternativa/tanks/game/entities/map/A3DMapComponent.as',
    'alternativa/tanks/game/entities/map/IA3DMapComponentListener.as',
    'alternativa/tanks/game/entities/map/MapMaterial.as',
    'alternativa/tanks/game/entities/map/MapOptions.as',
    'alternativa/tanks/game/entities/map/VisibleLightMaterial.as',
    'alternativa/tanks/game/entities/tank/BasicWeaponManualControlComponent.as',
    'alternativa/tanks/game/entities/tank/graphics/ActivatingState.as',
    'alternativa/tanks/game/entities/tank/graphics/ActiveState.as',
    'alternativa/tanks/game/entities/tank/graphics/chassis/tracked/TrackAnimator.as',
    'alternativa/tanks/game/entities/tank/graphics/chassis/tracked/TrackedChassisGraphicsComponent.as',
    'alternativa/tanks/game/entities/tank/graphics/ComponentState.as',
    'alternativa/tanks/game/entities/tank/graphics/DeadState.as',
    'alternativa/tanks/game/entities/tank/graphics/DirectionalShadowRendererConstructor.as',
    'alternativa/tanks/game/entities/tank/graphics/GraphicsControlComponent.as',
    'alternativa/tanks/game/entities/tank/graphics/IDirectionalShadowRendererConsumer.as',
    'alternativa/tanks/game/entities/tank/graphics/ITankGraphicsComponent.as',
    'alternativa/tanks/game/entities/tank/graphics/materials/GiShadowMaterial.as',
    'alternativa/tanks/game/entities/tank/graphics/materials/TankMaterial.as',
    'alternativa/tanks/game/entities/tank/graphics/materials/TankMaterial2.as',
    'alternativa/tanks/game/entities/tank/graphics/materials/TracksMaterial2.as',
    'alternativa/tanks/game/entities/tank/graphics/materials/TreesMaterial.as',
    'alternativa/tanks/game/entities/tank/graphics/MaterialType.as',
    'alternativa/tanks/game/entities/tank/graphics/PhysicsRendererComponent.as',
    'alternativa/tanks/game/entities/tank/graphics/RespawnState.as',
    'alternativa/tanks/game/entities/tank/graphics/TankExplosionComponent.as',
    'alternativa/tanks/game/entities/tank/graphics/turret/TurretGraphicsComponent.as',
    'alternativa/tanks/game/entities/tank/IActivatingStateCallback.as',
    'alternativa/tanks/game/entities/tank/IChassisManualControlCallback.as',
    'alternativa/tanks/game/entities/tank/IControllableTrackedChassisComponent.as',
    'alternativa/tanks/game/entities/tank/ITurretManualControlCallback.as',
    'alternativa/tanks/game/entities/tank/parsers/TankHullParser.as',
    'alternativa/tanks/game/entities/tank/parsers/TankPartParser.as',
    'alternativa/tanks/game/entities/tank/parsers/TankPartParsingUtils.as',
    'alternativa/tanks/game/entities/tank/parsers/TankTurretParser.as',
    'alternativa/tanks/game/entities/tank/physics/chassis/tracked/legacy/LegacyActivatingState.as',
    'alternativa/tanks/game/entities/tank/physics/chassis/tracked/legacy/LegacyActiveState.as',
    'alternativa/tanks/game/entities/tank/physics/chassis/tracked/legacy/LegacyComponentState.as',
    'alternativa/tanks/game/entities/tank/physics/chassis/tracked/legacy/LegacyDeadState.as',
    'alternativa/tanks/game/entities/tank/physics/chassis/tracked/legacy/LegacyRespawnState.as',
    'alternativa/tanks/game/entities/tank/physics/chassis/tracked/legacy/LegacySuspensionRay.as',
    'alternativa/tanks/game/entities/tank/physics/chassis/tracked/legacy/LegacyTrack.as',
    'alternativa/tanks/game/entities/tank/physics/chassis/tracked/legacy/LegacyTrackedChassisComponent.as',
    'alternativa/tanks/game/entities/tank/physics/chassis/tracked/legacy/SuspensionData.as',
    'alternativa/tanks/game/entities/tank/physics/IChassisPhysicsComponent.as',
    'alternativa/tanks/game/entities/tank/physics/InterpolationComponent.as',
    'alternativa/tanks/game/entities/tank/physics/ITurretPhysicsComponent.as',
    'alternativa/tanks/game/entities/tank/physics/turret/ActiveState.as',
    'alternativa/tanks/game/entities/tank/physics/turret/DeadState.as',
    'alternativa/tanks/game/entities/tank/physics/turret/RespawnState.as',
    'alternativa/tanks/game/entities/tank/physics/turret/TurretPhysicsComponent.as',
    'alternativa/tanks/game/entities/tank/TankControlComponent.as',
    'alternativa/tanks/game/entities/tank/TankEvents.as',
    'alternativa/tanks/game/entities/tank/TankGameState.as',
    'alternativa/tanks/game/entities/tank/TankHull.as',
    'alternativa/tanks/game/entities/tank/TankPart.as',
    'alternativa/tanks/game/entities/tank/TankPartMaterials.as',
    'alternativa/tanks/game/entities/tank/TankTurret.as',
    'alternativa/tanks/game/entities/tank/TankWheel.as',
    'alternativa/tanks/game/entities/tank/TrackedChassisManualControlComponent.as',
    'alternativa/tanks/game/entities/tank/TurretManualControlComponent.as',
    
    'alternativa/tanks/game/Entity.as',
    'alternativa/tanks/game/EntityComponent.as',
    'alternativa/tanks/game/GameEvents.as',
    'alternativa/tanks/game/GameKernel.as',
    'alternativa/tanks/game/GameTask.as',
    'alternativa/tanks/game/IGameLogger.as',
    'alternativa/tanks/game/ObjectController.as',
    'alternativa/tanks/game/TaskManager.as',
    
    'alternativa/tanks/game/physics/BodyCollisionData.as',
    'alternativa/tanks/game/physics/BodyDistance.as',
    'alternativa/tanks/game/physics/BoxData.as',
    'alternativa/tanks/game/physics/collision/uniformgrid/BodyCollisionGridData.as',
    'alternativa/tanks/game/physics/collision/uniformgrid/IRaycastCellVisitor.as',
    'alternativa/tanks/game/physics/collision/uniformgrid/UniformGridCollisionDetector.as',
    'alternativa/tanks/game/physics/CollisionGroup.as',
    'alternativa/tanks/game/physics/IRadiusQueryFilter.as',
    'alternativa/tanks/game/physics/ITanksCollisionDetector.as',
    'alternativa/tanks/game/physics/SimpleRaycastFilter.as',
    'alternativa/tanks/game/physics/TanksCollisionDetector.as',
    'alternativa/tanks/game/physics/TurretCollisioinBox.as',
    
    'alternativa/tanks/game/subsystems/battlemessages/BattleMessagesSubsystem.as',
    'alternativa/tanks/game/subsystems/deferredcommandssystem/DeferredCommand.as',
    'alternativa/tanks/game/subsystems/deferredcommandssystem/DeferredCommandsSystem.as',
    'alternativa/tanks/game/subsystems/eventsystem/EventSystem.as',
    'alternativa/tanks/game/subsystems/eventsystem/GameEvent.as',
    'alternativa/tanks/game/subsystems/eventsystem/IEventSystem.as',
    'alternativa/tanks/game/subsystems/eventsystem/IGameEventListener.as',
    'alternativa/tanks/game/subsystems/inputsystem/IInput.as',
    'alternativa/tanks/game/subsystems/inputsystem/InputSystem.as',
    'alternativa/tanks/game/subsystems/inputsystem/KeyboardEventType.as',
    'alternativa/tanks/game/subsystems/logicsystem/ILogic.as',
    'alternativa/tanks/game/subsystems/logicsystem/ILogicUnit.as',
    'alternativa/tanks/game/subsystems/logicsystem/LogicSystem.as',
    'alternativa/tanks/game/subsystems/physicssystem/IPhysicsController.as',
    'alternativa/tanks/game/subsystems/physicssystem/PhysicsSystem.as',
    'alternativa/tanks/game/subsystems/rendersystem/BlendedMaterial.as',
    'alternativa/tanks/game/subsystems/rendersystem/DirectionalLightList.as',
    'alternativa/tanks/game/subsystems/rendersystem/FogInitializator.as',
    'alternativa/tanks/game/subsystems/rendersystem/GameCamera.as',
    'alternativa/tanks/game/subsystems/rendersystem/ICameraController.as',
    'alternativa/tanks/game/subsystems/rendersystem/IDeferredAction.as',
    'alternativa/tanks/game/subsystems/rendersystem/IGraphicEffect.as',
    'alternativa/tanks/game/subsystems/rendersystem/IRenderer.as',
    'alternativa/tanks/game/subsystems/rendersystem/IResourceManager.as',
    'alternativa/tanks/game/subsystems/rendersystem/IShadowRendererConstructor.as',
    'alternativa/tanks/game/subsystems/rendersystem/Lights.as',
    'alternativa/tanks/game/subsystems/rendersystem/OmniLightList.as',
    'alternativa/tanks/game/subsystems/rendersystem/RendererList.as',
    'alternativa/tanks/game/subsystems/rendersystem/RenderSystem.as',
    'alternativa/tanks/game/subsystems/rendersystem/RenderUtils.as',
    'alternativa/tanks/game/subsystems/rendersystem/ResourceManager.as',
    'alternativa/tanks/game/subsystems/rendersystem/SkyMaterial.as',
    'alternativa/tanks/game/subsystems/rendersystem/SpotLightList.as',
    'alternativa/tanks/game/subsystems/rendersystem/StaticShadowInitializer.as',
    'alternativa/tanks/game/subsystems/rendersystem/TextMarker.as',
    'alternativa/tanks/game/subsystems/timesystem/TimeSystem.as',
    
    'alternativa/tanks/game/types/TeamType.as',
    
    'alternativa/tanks/game/usertitle/BarParts.as',
    'alternativa/tanks/game/usertitle/component/ComponentStateBase.as',
    'alternativa/tanks/game/usertitle/component/DeadState.as',
    'alternativa/tanks/game/usertitle/component/IUserName.as',
    'alternativa/tanks/game/usertitle/component/OffSceneState.as',
    'alternativa/tanks/game/usertitle/component/UserTitleComponent.as',
    'alternativa/tanks/game/usertitle/component/VisibleState.as',
    'alternativa/tanks/game/usertitle/EffectIndicator.as',
    'alternativa/tanks/game/usertitle/EffectIndicator_iconArmorCls.as',
    'alternativa/tanks/game/usertitle/EffectIndicator_iconHealthCls.as',
    'alternativa/tanks/game/usertitle/EffectIndicator_iconNitroCls.as',
    'alternativa/tanks/game/usertitle/EffectIndicator_iconPowerCls.as',
    'alternativa/tanks/game/usertitle/IRankIcon.as',
    'alternativa/tanks/game/usertitle/IUserTitleRenderer.as',
    'alternativa/tanks/game/usertitle/ProgressBar.as',
    'alternativa/tanks/game/usertitle/ProgressBarSkin.as',
    'alternativa/tanks/game/usertitle/ProgressBarSkin_hpBlueEmptyCls.as',
    'alternativa/tanks/game/usertitle/ProgressBarSkin_hpBlueFullCls.as',
    'alternativa/tanks/game/usertitle/ProgressBarSkin_hpGreenEmptyCls.as',
    'alternativa/tanks/game/usertitle/ProgressBarSkin_hpGreenFullCls.as',
    'alternativa/tanks/game/usertitle/ProgressBarSkin_hpRedEmptyCls.as',
    'alternativa/tanks/game/usertitle/ProgressBarSkin_hpRedFullCls.as',
    'alternativa/tanks/game/usertitle/ProgressBarSkin_weaponEmptyCls.as',
    'alternativa/tanks/game/usertitle/ProgressBarSkin_weaponFullCls.as',
    'alternativa/tanks/game/usertitle/UserTitle.as',
    
    'alternativa/tanks/game/utils/BitFlags.as',
    'alternativa/tanks/game/utils/BitVector.as',
    'alternativa/tanks/game/utils/datacache/DataCache.as',
    'alternativa/tanks/game/utils/datacache/IDataFactory.as',
    'alternativa/tanks/game/utils/GameMathUtils.as',
    'alternativa/tanks/game/utils/list/errors/ConcurrentModificationError.as',
    'alternativa/tanks/game/utils/list/errors/NoSuchElementError.as',
    'alternativa/tanks/game/utils/list/List.as',
    'alternativa/tanks/game/utils/list/ListItem.as',
    'alternativa/tanks/game/utils/list/ListIterator.as',
    'alternativa/tanks/game/utils/list/ListIteratorImpl.as',
    'alternativa/tanks/game/utils/objectpool/ObjectPool.as',
    'alternativa/tanks/game/utils/objectpool/ObjectPoolManager.as',
    'alternativa/tanks/game/utils/objectpool/PooledObject.as',
    'alternativa/tanks/game/utils/PhysicsParsingUtils.as',
    'alternativa/tanks/game/utils/SFXUtils.as',
    'alternativa/tanks/game/utils/Task.as',
    'alternativa/tanks/game/utils/TaskSequence.as',
    'alternativa/tanks/game/utils/TimeStat.as',
    
    'alternativa/tanks/game/weapons/ammunition/energy/EnergyAmmunitionComponent.as',
    'alternativa/tanks/game/weapons/ammunition/energy/EnergyRoundComponent.as',
    'alternativa/tanks/game/weapons/ammunition/energy/EnergyRoundData.as',
    'alternativa/tanks/game/weapons/ammunition/energy/IEnergyRoundCallback.as',
    'alternativa/tanks/game/weapons/ammunition/energy/IEnergyRoundEffect.as',
    'alternativa/tanks/game/weapons/ammunition/energy/IEnergyRoundEffectsFactory.as',
    'alternativa/tanks/game/weapons/ammunition/IAOEAmmunitionCallback.as',
    'alternativa/tanks/game/weapons/ammunition/plasma/PlasmaRoundEffect.as',
    'alternativa/tanks/game/weapons/ammunition/plasma/PlasmaRoundEffectsFactory.as',
    'alternativa/tanks/game/weapons/ammunition/pointhit/PointHitRound.as',
    'alternativa/tanks/game/weapons/ammunition/railgun/debug/DebugRailgunTargetEvaluator.as',
    'alternativa/tanks/game/weapons/ammunition/railgun/MultybodyRaycastFilter.as',
    'alternativa/tanks/game/weapons/ammunition/splashhit/debug/DebugSplashDamage.as',
    'alternativa/tanks/game/weapons/ammunition/splashhit/debug/DebugSplashDamageAmmo.as',
    'alternativa/tanks/game/weapons/ammunition/splashhit/debug/DebugSplashDamageEffects.as',
    'alternativa/tanks/game/weapons/ammunition/splashhit/debug/DebugSplashTargetFilter.as',
    'alternativa/tanks/game/weapons/ammunition/splashhit/debug/SmokyExplosion.as',
    'alternativa/tanks/game/weapons/ammunition/splashhit/debug/SmokyShot.as',
    'alternativa/tanks/game/weapons/ammunition/splashhit/ISplashDamage.as',
    'alternativa/tanks/game/weapons/ammunition/splashhit/ISplashTargetFilter.as',
    'alternativa/tanks/game/weapons/ammunition/splashhit/SplashDamageRound.as',
    'alternativa/tanks/game/weapons/conicareadamage/ConicAreaWeaponComponent.as',
    'alternativa/tanks/game/weapons/conicareadamage/IConicAreaWeaponCallback.as',
    'alternativa/tanks/game/weapons/conicareadamage/IConicAreaWeaponSFX.as',
    'alternativa/tanks/game/weapons/ContinuousActionGunPlatformComponent.as',
    'alternativa/tanks/game/weapons/debug/DebugWeaponDistanceWeakening.as',
    'alternativa/tanks/game/weapons/effects/IWeaponShotEffects.as',
    'alternativa/tanks/game/weapons/EnergyShotType.as',
    'alternativa/tanks/game/weapons/EnergyShotWeaponComponent.as',
    'alternativa/tanks/game/weapons/flamethrower/FlameThrower.as',
    'alternativa/tanks/game/weapons/flamethrower/FlamethrowerGraphicEffect.as',
    'alternativa/tanks/game/weapons/flamethrower/FlamethrowerSFXComponent.as',
    'alternativa/tanks/game/weapons/flamethrower/FlamethrowerSFXData.as',
    'alternativa/tanks/game/weapons/IBasicWeapon.as',
    'alternativa/tanks/game/weapons/IContinuousActionWeapon.as',
    'alternativa/tanks/game/weapons/IEnergyAmmunition.as',
    'alternativa/tanks/game/weapons/IEnergyShotWeaponCallback.as',
    'alternativa/tanks/game/weapons/IGenericAmmunition.as',
    'alternativa/tanks/game/weapons/IGenericRound.as',
    'alternativa/tanks/game/weapons/IGenericTargetingSystem.as',
    'alternativa/tanks/game/weapons/IInstantShotWeaponCallback.as',
    'alternativa/tanks/game/weapons/InstantShotWeaponComponent.as',
    'alternativa/tanks/game/weapons/IWeapon.as',
    'alternativa/tanks/game/weapons/IWeaponDistanceWeakening.as',
    'alternativa/tanks/game/weapons/railgun/IRailgunTargetEvaluator.as',
    'alternativa/tanks/game/weapons/SimpleTargetEvaluator.as',
    'alternativa/tanks/game/weapons/targeting/ConicAreaTargetingSystem.as',
    'alternativa/tanks/game/weapons/targeting/EnergyTargetingSystem.as',
    'alternativa/tanks/game/weapons/targeting/GenericTargetingSystem.as',
    'alternativa/tanks/game/weapons/targeting/IEnergyTargetingSystem.as',
    'alternativa/tanks/game/weapons/targeting/IGenericTargetEvaluator.as',
    'alternativa/tanks/game/weapons/targeting/RailgunTargetingSystem.as',
    'alternativa/tanks/game/weapons/thunder/effects/ThunderShotEffect.as',
    'alternativa/tanks/game/weapons/thunder/ThunderShotEffectComponent.as',
    'alternativa/tanks/game/weapons/WeaponConst.as',
    'alternativa/tanks/game/weapons/WeaponHit.as',
        
    'alternativa/tanks/lightsmanager/AmbientLightRegistry.as',
    'alternativa/tanks/lightsmanager/DirectionalLightRegistry.as',
    'alternativa/tanks/lightsmanager/LightsManager.as',
    'alternativa/tanks/lightsmanager/LightsRegistry.as',
    'alternativa/tanks/lightsmanager/OmniLightRegistry.as',
    'alternativa/tanks/lightsmanager/SpotLightRegistry.as',
    
    'alternativa/tanks/ITextureResourceService.as',
    'alternativa/tanks/TextureResourceService.as',
    
    'alternativa/tanks/utils/TARAParser.as',
    'alternativa/tanks/utils/Task.as',
    'alternativa/tanks/utils/TaskEvent.as',
    'alternativa/tanks/utils/TaskSequence.as',
    'alternativa/tanks/utils/TextureUtils.as',
    'alternativa/tanks/utils/XMLHelper.as',
    
    'alternativa/utils/ByteArrayMap.as',
    'alternativa/utils/ColorUtils.as',
    'alternativa/utils/KeyboardUtils.as',
    'alternativa/utils/MathUtils.as',
    'alternativa/utils/TextUtils.as'
)

lib_tanks = custom_target(
    'Tanks.swc',
    output: 'Tanks.swc',
    input: tanks_sources,
    command: [
        compc,
        '-source-path=' + meson.current_source_dir(),
        '-output=@OUTPUT@',
        
        '-external-library-path',
        lib_osgibase,
        lib_alternativaosgi,
        lib_alternativaprotocol,
        lib_alternativamath,
        lib_alternativaphysics,
        lib_alternativa3d,
        lib_a3dmodelsbase,
        
        '-include-sources',
        meson.current_source_dir(), # We can't use @INPUT@ because compc cries about having too many arguments,
                                    # keeping the file array because it allows meson to rebuild only on file edits.
                                    # Might be good to merge the file paths into a single "" but idk if that would work.

        '--'
    ],
    build_by_default: true
)
