alternativaclient_sources = files(
    'platform/client/fp10/core/osgi/ClientActivator.as',
    
    'platform/client/fp10/core/dispatcher/ClassDispatcherItem.as',
    'platform/client/fp10/core/dispatcher/Dispatcher.as',
    'platform/client/fp10/core/dispatcher/DispatcherItem.as',
    'platform/client/fp10/core/dispatcher/DispatcherItemId.as',
    'platform/client/fp10/core/dispatcher/IDispatcherListener.as',
    'platform/client/fp10/core/dispatcher/ResourceDispatcherItem.as',

    'platform/client/fp10/core/dumpers/ClassDumper.as',
    'platform/client/fp10/core/dumpers/ModelDumper.as',
    'platform/client/fp10/core/dumpers/ObjectDumper.as',
    'platform/client/fp10/core/dumpers/ResourceDumper.as',
    'platform/client/fp10/core/dumpers/SpaceDumper.as',
    
    'platform/client/fp10/core/model/IObjectLoadListener.as',
    'platform/client/fp10/core/model/IObjectLoadListenerAdapt.as',
    'platform/client/fp10/core/model/IObjectLoadListenerEvents.as',
    'platform/client/fp10/core/model/IModel.as',
    'platform/client/fp10/core/model/impl/Model.as',
    
    'platform/client/fp10/core/network/command/IServerControlCommand.as',
    'platform/client/fp10/core/network/command/ControlCommand.as',
    'platform/client/fp10/core/network/command/ServerMessageType.as',
    'platform/client/fp10/core/network/command/SpaceCommand.as',
    'platform/client/fp10/core/network/command/SpaceOpenedCommand.as',

    'platform/client/fp10/core/network/command/control/client/DependenciesLoadedCommand.as',
    'platform/client/fp10/core/network/command/control/client/HashRequestCommand.as',
    'platform/client/fp10/core/network/command/control/client/LoaderParamsCommand.as',
    'platform/client/fp10/core/network/command/control/client/LoaderParamsCommandCodec.as',
    'platform/client/fp10/core/network/command/control/client/LogCommand.as',
    'platform/client/fp10/core/network/command/control/client/LogCommandCodec.as',
    'platform/client/fp10/core/network/command/control/server/HashResponceCommand.as',
    'platform/client/fp10/core/network/command/control/server/HashResponceCommandCodec.as',
    'platform/client/fp10/core/network/command/control/server/LoadDependenciesCommand.as',
    'platform/client/fp10/core/network/command/control/server/LoadDependenciesCommandCodec.as',
    'platform/client/fp10/core/network/command/control/server/MessageCommand.as',
    'platform/client/fp10/core/network/command/control/server/OpenSpaceCommand.as',
    'platform/client/fp10/core/network/command/control/server/OpenSpaceCommandCodec.as',
    'platform/client/fp10/core/network/command/control/server/UnloadDependenciesCommand.as',
    'platform/client/fp10/core/network/command/control/server/UnloadDependenciesCommandCodec.as',

    'platform/client/fp10/core/network/Connection.as',
    'platform/client/fp10/core/network/ConnectionCloseStatus.as',
    'platform/client/fp10/core/network/ControlChannelContext.as',
    'platform/client/fp10/core/network/handler/ControlCommandHandler.as',
    'platform/client/fp10/core/network/handler/ISpaceCommandHandler.as',
    'platform/client/fp10/core/network/handler/SpaceCommandHandler.as',
    'platform/client/fp10/core/network/ICommandHandler.as',
    'platform/client/fp10/core/network/ICommandSender.as',
    
    'platform/client/fp10/core/protocol/codec/ControlRootCodec.as',
    'platform/client/fp10/core/protocol/codec/DispatcherItemCodec.as',
    'platform/client/fp10/core/protocol/codec/DispatcherItemIdCodec.as',
    'platform/client/fp10/core/protocol/codec/GameObjectCodec.as',
    'platform/client/fp10/core/protocol/codec/SpaceOpenedCommandCodec.as',
    'platform/client/fp10/core/protocol/codec/SpaceRootCodec.as',
    'platform/client/fp10/core/registry/GameTypeRegistry.as',
    'platform/client/fp10/core/registry/impl/DebugProgressIndicator.as',
    'platform/client/fp10/core/registry/impl/GameTypeRegistryImpl.as',
    'platform/client/fp10/core/registry/impl/ModelsRegistryImpl.as',
    'platform/client/fp10/core/registry/impl/ResourceRegistryImpl.as',
    'platform/client/fp10/core/registry/impl/SpaceRegistryImpl.as',
    'platform/client/fp10/core/registry/ModelRegistry.as',
    'platform/client/fp10/core/registry/ResourceRegistry.as',
    'platform/client/fp10/core/registry/SpaceRegistry.as',
    'platform/client/fp10/core/resource/BatchImageConstructor.as',
    'platform/client/fp10/core/resource/BatchResourceLoader.as',
    'platform/client/fp10/core/resource/IBatchResourceLoaderListener.as',
    'platform/client/fp10/core/resource/IResourceLoader.as',
    'platform/client/fp10/core/resource/IResourceLoadingListener.as',
    'platform/client/fp10/core/resource/IResourceLocalStorageInternal.as',
    'platform/client/fp10/core/resource/IResourceSerializationListener.as',
    'platform/client/fp10/core/resource/LibraryResourceWrapper.as',
    'platform/client/fp10/core/resource/Resource.as',
    'platform/client/fp10/core/resource/ResourceFileInfo.as',
    'platform/client/fp10/core/resource/ResourceFlags.as',
    'platform/client/fp10/core/resource/ResourceInfo.as',
    'platform/client/fp10/core/resource/ResourceLoader.as',
    'platform/client/fp10/core/resource/ResourceLocalStorage.as',
    'platform/client/fp10/core/resource/ResourcePriority.as',
    'platform/client/fp10/core/resource/ResourceStatus.as',
    'platform/client/fp10/core/resource/ResourceTimer.as',
    'platform/client/fp10/core/resource/ResourceType.as',
    'platform/client/fp10/core/resource/ResourceUtils.as',
    'platform/client/fp10/core/resource/SafeURLLoader.as',
    'platform/client/fp10/core/resource/tara/TARAParser.as',
    'platform/client/fp10/core/resource/types/ImageResource.as',
    'platform/client/fp10/core/resource/types/MultiframeImageResource.as',
    'platform/client/fp10/core/resource/types/Resource3DS.as',
    'platform/client/fp10/core/resource/types/SoundResource.as',
    'platform/client/fp10/core/resource/types/StubBitmapData.as',
    'platform/client/fp10/core/resource/types/SWFLibraryResource.as',
    'platform/client/fp10/core/service/address/AddressService.as',
    'platform/client/fp10/core/service/address/impl/AddressServiceImpl.as',
    'platform/client/fp10/core/service/IResourceTimer.as',
    'platform/client/fp10/core/service/loadingprogress/ILoadingProgressListener.as',
    'platform/client/fp10/core/service/loadingprogress/ILoadingProgressService.as',
    'platform/client/fp10/core/service/localstorage/IResourceLocalStorage.as',
    'platform/client/fp10/core/service/messagebox/IMessageBoxListener.as',
    'platform/client/fp10/core/service/messagebox/IMessageBoxService.as',
    'platform/client/fp10/core/service/messagebox/impl/MessageBoxService.as',
    'platform/client/fp10/core/service/messagebox/impl/MessageWindow.as',
    'platform/client/fp10/core/service/messagebox/MessageBoxButton.as',
    'platform/client/fp10/core/service/messagebox/MessageBoxType.as',
    'platform/client/fp10/core/service/serverlog/impl/DebugServerLogService.as',
    'platform/client/fp10/core/service/serverlog/impl/ErrorLog.as',
    'platform/client/fp10/core/service/serverlog/impl/ReleaseServerLogService.as',
    'platform/client/fp10/core/service/serverlog/IServerLog.as',
    'platform/client/fp10/core/service/serverlog/LogLevel.as',
    'platform/client/fp10/core/type/IGameClass.as',
    'platform/client/fp10/core/type/IGameObject.as',
    'platform/client/fp10/core/type/impl/GameClass.as',
    'platform/client/fp10/core/type/impl/GameObject.as',
    'platform/client/fp10/core/type/impl/Space.as',
    'platform/client/fp10/core/type/ISpace.as',
    'platform/clients/fp10/libraries/alternativaclient/Activator.as',

    'swfaddress/SWFAddress.as',
    'swfaddress/SWFAddressEvent.as',
    
    '_codec/platform/client/fp10/core/dispatcher/VectorCodecDispatcherItemLevel1.as',
    '_codec/platform/client/fp10/core/dispatcher/VectorCodecDispatcherItemLevel2.as',
    '_codec/platform/client/fp10/core/dispatcher/VectorCodecDispatcherItemLevel3.as',
    '_codec/platform/client/fp10/core/resource/types/VectorCodecMultiframeImageResourceLevel1.as',
    '_codec/platform/client/fp10/core/resource/types/VectorCodecMultiframeImageResourceLevel2.as',
    '_codec/platform/client/fp10/core/resource/types/VectorCodecMultiframeImageResourceLevel3.as',
    '_codec/platform/client/fp10/core/type/VectorCodecIGameObjectLevel1.as',
    '_codec/platform/client/fp10/core/type/VectorCodecIGameObjectLevel2.as',
    '_codec/platform/client/fp10/core/type/VectorCodecIGameObjectLevel3.as'
)

lib_alternativaclient = custom_target(
    'AlternativaClient.swc',
    output: 'AlternativaClient.swc',
    input: alternativaclient_sources,
    command: [
        compc,
        '-source-path=' + meson.current_source_dir(),
        '-output=@OUTPUT@',
        
        '-external-library-path',
        lib_osgibase,
        lib_alternativaosgi,
        lib_alternativaprotocol,
        lib_resourcemodelsbase,
        
        '-include-sources',
        meson.current_source_dir(), # We can't use @INPUT@ because compc cries about having too many arguments,
                                    # keeping the file array because it allows meson to rebuild only on file edits.
                                    # Might be good to merge the file paths into a single "" but idk if that would work.

        '--'
    ],
    build_by_default: true
)
