alternativa3d_sources = files(
    'alternativa/Alternativa3D.as',
    'alternativa/engine3d/alternativa3d.as',
    
    'alternativa/engine3d/animation/AnimationClip.as',
    'alternativa/engine3d/animation/AnimationController.as',
    'alternativa/engine3d/animation/AnimationNode.as',
    'alternativa/engine3d/animation/AnimationNotify.as',
    'alternativa/engine3d/animation/AnimationState.as',
    'alternativa/engine3d/animation/events/NotifyEvent.as',
    'alternativa/engine3d/animation/keys/Keyframe.as',
    'alternativa/engine3d/animation/keys/NumberKey.as',
    'alternativa/engine3d/animation/keys/NumberTrack.as',
    'alternativa/engine3d/animation/keys/Track.as',
    'alternativa/engine3d/animation/keys/TransformKey.as',
    'alternativa/engine3d/animation/keys/TransformTrack.as',
    
    'alternativa/engine3d/collisions/EllipsoidCollider.as',
    
    'alternativa/engine3d/core/BoundBox.as',
    'alternativa/engine3d/core/Camera3D.as',
    'alternativa/engine3d/core/CullingPlane.as',
    'alternativa/engine3d/core/Debug.as',
    'alternativa/engine3d/core/DrawUnit.as',
    'alternativa/engine3d/core/events/Event3D.as',
    'alternativa/engine3d/core/events/MouseEvent3D.as',
    'alternativa/engine3d/core/Light3D.as',
    'alternativa/engine3d/core/Object3D.as',
    'alternativa/engine3d/core/Occluder.as',
    'alternativa/engine3d/core/RayIntersectionData.as',
    'alternativa/engine3d/core/Renderer.as',
    'alternativa/engine3d/core/RenderPriority.as',
    'alternativa/engine3d/core/Resource.as',
    'alternativa/engine3d/core/Transform3D.as',
    'alternativa/engine3d/core/VertexAttributes.as',
    'alternativa/engine3d/core/VertexStream.as',
    'alternativa/engine3d/core/View.as',
    
    'alternativa/engine3d/effects/Particle.as',
    'alternativa/engine3d/effects/ParticleEffect.as',
    'alternativa/engine3d/effects/ParticlePrototype.as',
    'alternativa/engine3d/effects/ParticleSystem.as',
    'alternativa/engine3d/effects/TextureAtlas.as',
    
    'alternativa/engine3d/lights/AmbientLight.as',
    'alternativa/engine3d/lights/DirectionalLight.as',
    'alternativa/engine3d/lights/OmniLight.as',
    'alternativa/engine3d/lights/SpotLight.as',
    
    'alternativa/engine3d/loaders/ParserA3D.as',
    'alternativa/engine3d/loaders/ParserCollada.as',
    'alternativa/engine3d/loaders/ParserMaterial.as',
    'alternativa/engine3d/loaders/collada/collada.as',
    'alternativa/engine3d/loaders/collada/DaeArray.as',
    'alternativa/engine3d/loaders/collada/DaeChannel.as',
    'alternativa/engine3d/loaders/collada/DaeController.as',
    'alternativa/engine3d/loaders/collada/DaeDocument.as',
    'alternativa/engine3d/loaders/collada/DaeEffect.as',
    'alternativa/engine3d/loaders/collada/DaeEffectParam.as',
    'alternativa/engine3d/loaders/collada/DaeElement.as',
    'alternativa/engine3d/loaders/collada/DaeGeometry.as',
    'alternativa/engine3d/loaders/collada/DaeImage.as',
    'alternativa/engine3d/loaders/collada/DaeInput.as',
    'alternativa/engine3d/loaders/collada/DaeInstanceController.as',
    'alternativa/engine3d/loaders/collada/DaeInstanceMaterial.as',
    'alternativa/engine3d/loaders/collada/DaeLight.as',
    'alternativa/engine3d/loaders/collada/DaeLogger.as',
    'alternativa/engine3d/loaders/collada/DaeMaterial.as',
    'alternativa/engine3d/loaders/collada/DaeNode.as',
    'alternativa/engine3d/loaders/collada/DaeObject.as',
    'alternativa/engine3d/loaders/collada/DaeParam.as',
    'alternativa/engine3d/loaders/collada/DaePrimitive.as',
    'alternativa/engine3d/loaders/collada/DaeSampler.as',
    'alternativa/engine3d/loaders/collada/DaeSource.as',
    'alternativa/engine3d/loaders/collada/DaeVertex.as',
    'alternativa/engine3d/loaders/collada/DaeVertices.as',
    'alternativa/engine3d/loaders/collada/DaeVisualScene.as',
    
    'alternativa/engine3d/materials/EnviromentMaterial.as',
    'alternativa/engine3d/materials/FillMaterial.as',
    'alternativa/engine3d/materials/FogMode.as',
    'alternativa/engine3d/materials/Material.as',
    'alternativa/engine3d/materials/NormalMapSpace.as',
    'alternativa/engine3d/materials/ShaderProgram.as',
    'alternativa/engine3d/materials/StandardMaterial.as',
    'alternativa/engine3d/materials/TextureFormat.as',
    'alternativa/engine3d/materials/TextureMaterial.as',
    'alternativa/engine3d/materials/A3DUtils.as',

    'alternativa/engine3d/materials/compiler/CommandType.as',
    'alternativa/engine3d/materials/compiler/DestinationVariable.as',
    'alternativa/engine3d/materials/compiler/Linker.as',
    'alternativa/engine3d/materials/compiler/Procedure.as',
    'alternativa/engine3d/materials/compiler/RelativeVariable.as',
    'alternativa/engine3d/materials/compiler/SamplerVariable.as',
    'alternativa/engine3d/materials/compiler/SourceVariable.as',
    'alternativa/engine3d/materials/compiler/Variable.as',
    'alternativa/engine3d/materials/compiler/VariableType.as',
    
    'alternativa/engine3d/objects/Decal.as',
    'alternativa/engine3d/objects/Joint.as',
    'alternativa/engine3d/objects/Mesh.as',
    'alternativa/engine3d/objects/Skin.as',
    'alternativa/engine3d/objects/SkyBox.as',
    'alternativa/engine3d/objects/Sprite3D.as',
    'alternativa/engine3d/objects/Surface.as',
    'alternativa/engine3d/objects/WireFrame.as',
    
    'alternativa/engine3d/primitives/Box.as',
    
    'alternativa/engine3d/resources/ATFTextureResource.as',
    'alternativa/engine3d/resources/BitmapCubeTextureResource.as',
    'alternativa/engine3d/resources/BitmapTextureResource.as',
    'alternativa/engine3d/resources/ExternalTextureResource.as',
    'alternativa/engine3d/resources/Geometry.as',
    'alternativa/engine3d/resources/TextureResource.as',
    'alternativa/engine3d/resources/WireGeometry.as',
    
    'alternativa/engine3d/shadows/DirectionalShadowRenderer.as',
    'alternativa/engine3d/shadows/ShadowRenderer.as',
    'alternativa/engine3d/shadows/ShadowsSystem.as',
    'alternativa/engine3d/shadows/StaticShadowRenderer.as',

    meson.project_source_root() / 'external/AGALMiniAssembler/com/adobe/utils/AGALMiniAssembler.as'
)

lib_alternativa3d = custom_target(
    'Alternativa3D.swc',
    output: 'Alternativa3D.swc',
    input: alternativa3d_sources,
    command: [
        compc,
        '-source-path=' + meson.current_source_dir(),
        '-output=@OUTPUT@',
        
        '-external-library-path',
        lib_osgibase,
        lib_alternativaosgi,
        lib_alternativaprotocol,
        lib_a3dmodelsbase,
        
        '-include-sources',
        meson.project_source_root() / 'external/AGALMiniAssembler/com/adobe/utils/AGALMiniAssembler.as',
        meson.current_source_dir(), # We can't use @INPUT@ because compc cries about having too many arguments,
                                    # keeping the file array because it allows meson to rebuild only on file edits.
                                    # Might be good to merge the file paths into a single "" but idk if that would work.

        '--'
    ],
    build_by_default: true
)
