a3dmodelsbase_sources = files(
    # Activators
    'platform/client/a3d/osgi/Activator.as',

    # A3D data
    'commons/A3DMatrix.as',
    'commons/Id.as',
    
    'versions/version1/a3d/A3D.as',
    'versions/version1/a3d/geometry/A3DGeometry.as',
    'versions/version1/a3d/geometry/A3DIndexBuffer.as',
    'versions/version1/a3d/geometry/A3DVertexBuffer.as',
    'versions/version1/a3d/id/ParentId.as',
    'versions/version1/a3d/materials/A3DImage.as',
    'versions/version1/a3d/materials/A3DMap.as',
    'versions/version1/a3d/materials/A3DMaterial.as',
    'versions/version1/a3d/objects/A3DBox.as',
    'versions/version1/a3d/objects/A3DObject.as',
    'versions/version1/a3d/objects/A3DSurface.as',
    'versions/version1/a3d/objects/A3DTransformation.as',
    
    'versions/version2/a3d/A3D2.as',
    'versions/version2/a3d/animation/A3D2AnimationClip.as',
    'versions/version2/a3d/animation/A3D2Keyframe.as',
    'versions/version2/a3d/animation/A3D2Track.as',
    'versions/version2/a3d/geometry/A3D2IndexBuffer.as',
    'versions/version2/a3d/geometry/A3D2VertexAttributes.as',
    'versions/version2/a3d/geometry/A3D2VertexBuffer.as',
    'versions/version2/a3d/materials/A3D2CubeMap.as',
    'versions/version2/a3d/materials/A3D2Image.as',
    'versions/version2/a3d/materials/A3D2Map.as',
    'versions/version2/a3d/materials/A3D2Material.as',
    'versions/version2/a3d/objects/A3D2AmbientLight.as',
    'versions/version2/a3d/objects/A3D2Box.as',
    'versions/version2/a3d/objects/A3D2Decal.as',
    'versions/version2/a3d/objects/A3D2DirectionalLight.as',
    'versions/version2/a3d/objects/A3D2Joint.as',
    'versions/version2/a3d/objects/A3D2JointBindTransform.as',
    'versions/version2/a3d/objects/A3D2Mesh.as',
    'versions/version2/a3d/objects/A3D2Object.as',
    'versions/version2/a3d/objects/A3D2OmniLight.as',
    'versions/version2/a3d/objects/A3D2Skin.as',
    'versions/version2/a3d/objects/A3D2SpotLight.as',
    'versions/version2/a3d/objects/A3D2Sprite.as',
    'versions/version2/a3d/objects/A3D2Surface.as',
    'versions/version2/a3d/objects/A3D2Transform.as',
    
    # Codec
    '_codec/commons/CodecA3DMatrix.as',
    '_codec/commons/CodecId.as',
    '_codec/commons/VectorCodecA3DMatrixLevel1.as',
    '_codec/commons/VectorCodecA3DMatrixLevel2.as',
    '_codec/commons/VectorCodecA3DMatrixLevel3.as',
    '_codec/commons/VectorCodecIdLevel1.as',
    '_codec/commons/VectorCodecIdLevel2.as',
    '_codec/commons/VectorCodecIdLevel3.as',

    '_codec/versions/version1/a3d/CodecA3D.as',
    '_codec/versions/version1/a3d/geometry/CodecA3DGeometry.as',
    '_codec/versions/version1/a3d/geometry/CodecA3DIndexBuffer.as',
    '_codec/versions/version1/a3d/geometry/CodecA3DVertexBuffer.as',
    '_codec/versions/version1/a3d/geometry/VectorCodecA3DGeometryLevel1.as',
    '_codec/versions/version1/a3d/geometry/VectorCodecA3DGeometryLevel2.as',
    '_codec/versions/version1/a3d/geometry/VectorCodecA3DGeometryLevel3.as',
    '_codec/versions/version1/a3d/geometry/VectorCodecA3DIndexBufferLevel1.as',
    '_codec/versions/version1/a3d/geometry/VectorCodecA3DIndexBufferLevel2.as',
    '_codec/versions/version1/a3d/geometry/VectorCodecA3DIndexBufferLevel3.as',
    '_codec/versions/version1/a3d/geometry/VectorCodecA3DVertexBufferLevel1.as',
    '_codec/versions/version1/a3d/geometry/VectorCodecA3DVertexBufferLevel2.as',
    '_codec/versions/version1/a3d/geometry/VectorCodecA3DVertexBufferLevel3.as',
    '_codec/versions/version1/a3d/id/CodecParentId.as',
    '_codec/versions/version1/a3d/id/VectorCodecParentIdLevel1.as',
    '_codec/versions/version1/a3d/id/VectorCodecParentIdLevel2.as',
    '_codec/versions/version1/a3d/id/VectorCodecParentIdLevel3.as',
    '_codec/versions/version1/a3d/materials/CodecA3DImage.as',
    '_codec/versions/version1/a3d/materials/CodecA3DMap.as',
    '_codec/versions/version1/a3d/materials/CodecA3DMaterial.as',
    '_codec/versions/version1/a3d/materials/VectorCodecA3DImageLevel1.as',
    '_codec/versions/version1/a3d/materials/VectorCodecA3DImageLevel2.as',
    '_codec/versions/version1/a3d/materials/VectorCodecA3DImageLevel3.as',
    '_codec/versions/version1/a3d/materials/VectorCodecA3DMapLevel1.as',
    '_codec/versions/version1/a3d/materials/VectorCodecA3DMapLevel2.as',
    '_codec/versions/version1/a3d/materials/VectorCodecA3DMapLevel3.as',
    '_codec/versions/version1/a3d/materials/VectorCodecA3DMaterialLevel1.as',
    '_codec/versions/version1/a3d/materials/VectorCodecA3DMaterialLevel2.as',
    '_codec/versions/version1/a3d/materials/VectorCodecA3DMaterialLevel3.as',
    '_codec/versions/version1/a3d/objects/CodecA3DBox.as',
    '_codec/versions/version1/a3d/objects/CodecA3DObject.as',
    '_codec/versions/version1/a3d/objects/CodecA3DSurface.as',
    '_codec/versions/version1/a3d/objects/CodecA3DTransformation.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DBoxLevel1.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DBoxLevel2.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DBoxLevel3.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DObjectLevel1.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DObjectLevel2.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DObjectLevel3.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DSurfaceLevel1.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DSurfaceLevel2.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DSurfaceLevel3.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DTransformationLevel1.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DTransformationLevel2.as',
    '_codec/versions/version1/a3d/objects/VectorCodecA3DTransformationLevel3.as',
    '_codec/versions/version1/a3d/VectorCodecA3DLevel1.as',
    '_codec/versions/version1/a3d/VectorCodecA3DLevel2.as',
    '_codec/versions/version1/a3d/VectorCodecA3DLevel3.as',

    '_codec/versions/version2/a3d/animation/CodecA3D2AnimationClip.as',
    '_codec/versions/version2/a3d/animation/CodecA3D2Keyframe.as',
    '_codec/versions/version2/a3d/animation/CodecA3D2Track.as',
    '_codec/versions/version2/a3d/animation/VectorCodecA3D2AnimationClipLevel1.as',
    '_codec/versions/version2/a3d/animation/VectorCodecA3D2AnimationClipLevel2.as',
    '_codec/versions/version2/a3d/animation/VectorCodecA3D2AnimationClipLevel3.as',
    '_codec/versions/version2/a3d/animation/VectorCodecA3D2KeyframeLevel1.as',
    '_codec/versions/version2/a3d/animation/VectorCodecA3D2KeyframeLevel2.as',
    '_codec/versions/version2/a3d/animation/VectorCodecA3D2KeyframeLevel3.as',
    '_codec/versions/version2/a3d/animation/VectorCodecA3D2TrackLevel1.as',
    '_codec/versions/version2/a3d/animation/VectorCodecA3D2TrackLevel2.as',
    '_codec/versions/version2/a3d/animation/VectorCodecA3D2TrackLevel3.as',
    '_codec/versions/version2/a3d/CodecA3D2.as',
    '_codec/versions/version2/a3d/geometry/CodecA3D2IndexBuffer.as',
    '_codec/versions/version2/a3d/geometry/CodecA3D2VertexAttributes.as',
    '_codec/versions/version2/a3d/geometry/CodecA3D2VertexBuffer.as',
    '_codec/versions/version2/a3d/geometry/VectorCodecA3D2IndexBufferLevel1.as',
    '_codec/versions/version2/a3d/geometry/VectorCodecA3D2IndexBufferLevel2.as',
    '_codec/versions/version2/a3d/geometry/VectorCodecA3D2IndexBufferLevel3.as',
    '_codec/versions/version2/a3d/geometry/VectorCodecA3D2VertexAttributesLevel1.as',
    '_codec/versions/version2/a3d/geometry/VectorCodecA3D2VertexAttributesLevel2.as',
    '_codec/versions/version2/a3d/geometry/VectorCodecA3D2VertexAttributesLevel3.as',
    '_codec/versions/version2/a3d/geometry/VectorCodecA3D2VertexBufferLevel1.as',
    '_codec/versions/version2/a3d/geometry/VectorCodecA3D2VertexBufferLevel2.as',
    '_codec/versions/version2/a3d/geometry/VectorCodecA3D2VertexBufferLevel3.as',
    '_codec/versions/version2/a3d/materials/CodecA3D2CubeMap.as',
    '_codec/versions/version2/a3d/materials/CodecA3D2Image.as',
    '_codec/versions/version2/a3d/materials/CodecA3D2Map.as',
    '_codec/versions/version2/a3d/materials/CodecA3D2Material.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2CubeMapLevel1.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2CubeMapLevel2.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2CubeMapLevel3.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2ImageLevel1.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2ImageLevel2.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2ImageLevel3.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2MapLevel1.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2MapLevel2.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2MapLevel3.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2MaterialLevel1.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2MaterialLevel2.as',
    '_codec/versions/version2/a3d/materials/VectorCodecA3D2MaterialLevel3.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2AmbientLight.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2Box.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2Decal.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2DirectionalLight.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2Joint.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2JointBindTransform.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2Mesh.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2Object.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2OmniLight.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2Skin.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2SpotLight.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2Sprite.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2Surface.as',
    '_codec/versions/version2/a3d/objects/CodecA3D2Transform.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2AmbientLightLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2AmbientLightLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2AmbientLightLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2BoxLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2BoxLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2BoxLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2DecalLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2DecalLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2DecalLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2DirectionalLightLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2DirectionalLightLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2DirectionalLightLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2JointBindTransformLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2JointBindTransformLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2JointBindTransformLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2JointLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2JointLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2JointLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2MeshLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2MeshLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2MeshLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2ObjectLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2ObjectLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2ObjectLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2OmniLightLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2OmniLightLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2OmniLightLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SkinLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SkinLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SkinLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SpotLightLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SpotLightLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SpotLightLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SpriteLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SpriteLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SpriteLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SurfaceLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SurfaceLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2SurfaceLevel3.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2TransformLevel1.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2TransformLevel2.as',
    '_codec/versions/version2/a3d/objects/VectorCodecA3D2TransformLevel3.as',
    '_codec/versions/version2/a3d/VectorCodecA3D2Level1.as',
    '_codec/versions/version2/a3d/VectorCodecA3D2Level2.as',
    '_codec/versions/version2/a3d/VectorCodecA3D2Level3.as'
)

lib_a3dmodelsbase = custom_target(
    'A3DModelsBase.swc',
    output: 'A3DModelsBase.swc',
    input: a3dmodelsbase_sources,
    command: [
        compc,
        '-source-path=' + meson.current_source_dir(),
        '-output=@OUTPUT@',
        
        '-external-library-path',
        lib_osgibase,
        lib_alternativaosgi,
        lib_alternativaprotocol,
        
        '-include-sources',
        meson.current_source_dir(), # We can't use @INPUT@ because compc cries about having too many arguments,
                                    # keeping the file array because it allows meson to rebuild only on file edits.
                                    # Might be good to merge the file paths into a single "" but idk if that would work.

        '--'
    ],
    build_by_default: true
)
