package platform.client.core.general.resource.osgi
{
   import _codec.platform.core.general.resource.types.image.CodecResourceImageParams;
   import _codec.platform.core.general.resource.types.image.VectorCodecResourceImageParamsLevel1;
   import _codec.platform.core.general.resource.types.image.VectorCodecResourceImageParamsLevel2;
   import _codec.platform.core.general.resource.types.image.VectorCodecResourceImageParamsLevel3;
   import _codec.platform.core.general.resource.types.imageframe.CodecResourceImageFrameParams;
   import _codec.platform.core.general.resource.types.imageframe.VectorCodecResourceImageFrameParamsLevel1;
   import _codec.platform.core.general.resource.types.imageframe.VectorCodecResourceImageFrameParamsLevel2;
   import _codec.platform.core.general.resource.types.imageframe.VectorCodecResourceImageFrameParamsLevel3;
   import _codec.platform.core.general.resource.types.l10n.protocol.CodecBooleanPair;
   import _codec.platform.core.general.resource.types.l10n.protocol.CodecDoublePair;
   import _codec.platform.core.general.resource.types.l10n.protocol.CodecImagePair;
   import _codec.platform.core.general.resource.types.l10n.protocol.CodecIntPair;
   import _codec.platform.core.general.resource.types.l10n.protocol.CodecLocaleStruct;
   import _codec.platform.core.general.resource.types.l10n.protocol.CodecStringPair;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecBooleanPairLevel1;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecBooleanPairLevel2;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecBooleanPairLevel3;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecDoublePairLevel1;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecDoublePairLevel2;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecDoublePairLevel3;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecImagePairLevel1;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecImagePairLevel2;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecImagePairLevel3;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecIntPairLevel1;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecIntPairLevel2;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecIntPairLevel3;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecLocaleStructLevel1;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecLocaleStructLevel2;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecLocaleStructLevel3;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecStringPairLevel1;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecStringPairLevel2;
   import _codec.platform.core.general.resource.types.l10n.protocol.VectorCodecStringPairLevel3;
   import _codec.platform.core.general.resource.types.swf.CodecResourceSWFParams;
   import _codec.platform.core.general.resource.types.swf.VectorCodecResourceSWFParamsLevel1;
   import _codec.platform.core.general.resource.types.swf.VectorCodecResourceSWFParamsLevel2;
   import _codec.platform.core.general.resource.types.swf.VectorCodecResourceSWFParamsLevel3;
   import alternativa.osgi.OSGi;
   import alternativa.osgi.bundle.IBundleActivator;
   import alternativa.protocol.ICodec;
   import alternativa.protocol.IProtocol;
   import alternativa.protocol.codec.OptionalCodecDecorator;
   import alternativa.protocol.info.CollectionCodecInfo;
   import alternativa.protocol.info.TypeCodecInfo;
   import platform.core.general.resource.types.image.ResourceImageParams;
   import platform.core.general.resource.types.imageframe.ResourceImageFrameParams;
   import platform.core.general.resource.types.l10n.protocol.BooleanPair;
   import platform.core.general.resource.types.l10n.protocol.DoublePair;
   import platform.core.general.resource.types.l10n.protocol.ImagePair;
   import platform.core.general.resource.types.l10n.protocol.IntPair;
   import platform.core.general.resource.types.l10n.protocol.LocaleStruct;
   import platform.core.general.resource.types.l10n.protocol.StringPair;
   import platform.core.general.resource.types.swf.ResourceSWFParams;
   
   public class Activator implements IBundleActivator
   {
      
      public static var osgi:OSGi;
      
      public function Activator()
      {
         super();
      }
      
      public function start(param1:OSGi) : void
      {
         var _loc3_:ICodec = null;
         osgi = param1;
         var _loc2_:IProtocol = IProtocol(osgi.getService(IProtocol));
         _loc3_ = new CodecResourceImageFrameParams();
         _loc2_.registerCodec(new TypeCodecInfo(ResourceImageFrameParams,false),_loc3_);
         _loc2_.registerCodec(new TypeCodecInfo(ResourceImageFrameParams,true),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new CodecImagePair();
         _loc2_.registerCodec(new TypeCodecInfo(ImagePair,false),_loc3_);
         _loc2_.registerCodec(new TypeCodecInfo(ImagePair,true),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new CodecLocaleStruct();
         _loc2_.registerCodec(new TypeCodecInfo(LocaleStruct,false),_loc3_);
         _loc2_.registerCodec(new TypeCodecInfo(LocaleStruct,true),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new CodecDoublePair();
         _loc2_.registerCodec(new TypeCodecInfo(DoublePair,false),_loc3_);
         _loc2_.registerCodec(new TypeCodecInfo(DoublePair,true),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new CodecIntPair();
         _loc2_.registerCodec(new TypeCodecInfo(IntPair,false),_loc3_);
         _loc2_.registerCodec(new TypeCodecInfo(IntPair,true),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new CodecBooleanPair();
         _loc2_.registerCodec(new TypeCodecInfo(BooleanPair,false),_loc3_);
         _loc2_.registerCodec(new TypeCodecInfo(BooleanPair,true),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new CodecStringPair();
         _loc2_.registerCodec(new TypeCodecInfo(StringPair,false),_loc3_);
         _loc2_.registerCodec(new TypeCodecInfo(StringPair,true),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new CodecResourceSWFParams();
         _loc2_.registerCodec(new TypeCodecInfo(ResourceSWFParams,false),_loc3_);
         _loc2_.registerCodec(new TypeCodecInfo(ResourceSWFParams,true),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new CodecResourceImageParams();
         _loc2_.registerCodec(new TypeCodecInfo(ResourceImageParams,false),_loc3_);
         _loc2_.registerCodec(new TypeCodecInfo(ResourceImageParams,true),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecStringPairLevel2(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,false),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,false),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecStringPairLevel2(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,true),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,true),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecLocaleStructLevel3(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,false),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,false),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecLocaleStructLevel3(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,true),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,true),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecImagePairLevel3(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,false),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,false),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecImagePairLevel3(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,true),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,true),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageFrameParamsLevel3(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,false),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,false),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageFrameParamsLevel3(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,true),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,true),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageFrameParamsLevel1(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,false),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,false),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageFrameParamsLevel1(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,true),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,true),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceSWFParamsLevel2(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,false),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,false),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceSWFParamsLevel2(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,true),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,true),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageParamsLevel1(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,false),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,false),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageParamsLevel1(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,true),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,true),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecIntPairLevel1(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,false),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,false),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecIntPairLevel1(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,true),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,true),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecDoublePairLevel1(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,false),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,false),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecDoublePairLevel1(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,true),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,true),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecImagePairLevel1(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,false),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,false),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecImagePairLevel1(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,true),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,true),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceSWFParamsLevel1(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,false),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,false),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceSWFParamsLevel1(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,true),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,true),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecBooleanPairLevel2(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,false),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,false),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecBooleanPairLevel2(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,true),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,true),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageParamsLevel3(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,false),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,false),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageParamsLevel3(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,true),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,true),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecBooleanPairLevel3(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,false),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,false),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecBooleanPairLevel3(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,true),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,true),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecDoublePairLevel3(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,false),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,false),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecDoublePairLevel3(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,true),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,true),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecLocaleStructLevel1(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,false),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,false),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecLocaleStructLevel1(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,true),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,true),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageFrameParamsLevel2(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,false),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,false),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageFrameParamsLevel2(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,true),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageFrameParams,true),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecIntPairLevel3(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,false),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,false),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecIntPairLevel3(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,true),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,true),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecStringPairLevel1(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,false),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,false),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecStringPairLevel1(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,true),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,true),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecBooleanPairLevel1(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,false),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,false),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecBooleanPairLevel1(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,true),false,1),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BooleanPair,true),true,1),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageParamsLevel2(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,false),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,false),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceImageParamsLevel2(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,true),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceImageParams,true),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecIntPairLevel2(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,false),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,false),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecIntPairLevel2(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,true),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(IntPair,true),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceSWFParamsLevel3(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,false),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,false),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecResourceSWFParamsLevel3(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,true),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ResourceSWFParams,true),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecDoublePairLevel2(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,false),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,false),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecDoublePairLevel2(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,true),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DoublePair,true),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecStringPairLevel3(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,false),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,false),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecStringPairLevel3(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,true),false,3),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StringPair,true),true,3),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecLocaleStructLevel2(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,false),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,false),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecLocaleStructLevel2(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,true),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(LocaleStruct,true),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecImagePairLevel2(false);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,false),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,false),true,2),new OptionalCodecDecorator(_loc3_));
         _loc3_ = new VectorCodecImagePairLevel2(true);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,true),false,2),_loc3_);
         _loc2_.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ImagePair,true),true,2),new OptionalCodecDecorator(_loc3_));
      }
      
      public function stop(param1:OSGi) : void
      {
      }
   }
}

